project:
  type: website
  pre-render: "python -m quartodoc"

filters:
  - "interlinks"

website:
  title: "Vetiver API docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: reference/index.qmd
        text: Reference

  sidebar:
    - id: api
      title: Get Started
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - href: reference/index.qmd
        - href: api/compute_metrics.md
        - href: api/write_app.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

interlinks:
  sources:
    vetiver:
      url: "/"
      inv: null
      fallback: objects.json

quartodoc:
  style: pkgdown
  dir: reference
  package: vetiver
  sections:
    # TODO: figure out preface and Advanced Usage section
    - title: ""
      desc: ""
      contents:
        - VetiverModel
        - vetiver_pin_write
        - vetiver_create_ptype
        # - model_card

    - title: Deploy
      desc: ""
      contents:
        - VetiverAPI
        # - VetiverAPI.run
        # - VetiverAPI.vetiver_post
        - vetiver_endpoint
        - predict
        - write_app
        # - write_docker
        - deploy_rsconnect

    - title: Monitor
      desc: ""
      contents:
        - compute_metrics
        - pin_metrics
        - plot_metrics

    - title: Model Handlers
      desc: ""
      contents:
        - SKLearnHandler
        - TorchHandler
        - StatsmodelsHandler
        - XGBoostHandler

